version: "3"

services:
 istumfc:
    container_name: istumfc
    image: tebenkov2222/mfcistu:0.2
    restart: always  
    ports:
      - 80:80
    environment:
      TZ: "Europe/Samara"
      command: >
        sh -c "ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && 
        echo $TZ > /etc/timezone &&
        exec my-main-application"